[package]
name = "sample"
description = "A sample project to demonstrate how to use fli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "3.0.0"
fli = { path = "../" }
